### ISSUE TITLE
Feature Request: Gist JSON

### ISSUE THREAD

**Issue by Aetherinox** [thomiceli/opengist#107]
love the app, but if I could possibly request one feature that I would love to see.

Github gist's have the ability to add .JSON at the end of a gist URL, and you'll get a json formatted version which shows the creation date, the body, author, etc.

Would there be any possible way we could get this added to the TODO list? As an example, I took a random gist URL from someone.
You can view the gist via [https://gist.github.com/lbialy/44e627ff17034b1fb53b6a75f35ed9ac](https://gist.github.com/lbialy/44e627ff17034b1fb53b6a75f35ed9ac)

However, if you go to https://gist.github.com/lbialy/44e627ff17034b1fb53b6a75f35ed9ac.json, you can view various pieces of info about the gist, but in json format. It would help with pulling gists from 3rd party programs immensely. 

The cool part of the json is that it includes a `div` value, which is premade HTML to show the gist in a github styled box. Then I can pull that .json URL from other programs and it will integrate the code box and contents inside my program.

And then there's a `stylesheet` value which leads to something like https://github.githubassets.com/assets/gist-embed-3c6bff8100e5.css

With a 3rd party program, I can use javascript to include that CSS file from the JSON, and then pull the contents of `div` and display the gist box anywhere I use the javascript.

**Comment by thomiceli** [comment]
> The cool part of the json is that it includes a `div` value, which is premade HTML to show the gist in a github styled box. Then I can pull that .json URL from other programs and it will integrate the code box and contents inside my program.

This is something I also wanted to implement (regardless of the json part), but I had trouble to make it work. Will definitely implement this in the future.

**Comment by Aetherinox** [comment]
Thanks. The json with the DIV would be a huge thing if possible. I thought about coding it (web developer by trade), but I haven't screwed with an anounce of Go, just PHP, JS.
