### ISSUE TITLE
Clicking gist "Revisions" tab causing 502 Bad Gateway

### ISSUE THREAD

**Issue by Aetherinox** [thomiceli/opengist#116]
I am currently on the latest version of Opengist (v1.5.0). I was testing out private gists today and noticed the **revisions** tab which says I have two.

![meuAF11](https://github.com/thomiceli/opengist/assets/118329232/fdb78a3e-14a5-48c0-997d-f63368171519)

As soon as I click that link, the website automatically loads a 502 Bad Gateway for the url `https://gist.domain.com/username/0e36f42c247a56c1b224a4c2b16fd2ed/revisions` (this is all from a user computer).

I then connected to my server box using Remote Desktop and went to the website via `http://localhost:6157/`, signed in, went to the revisions tab and the server's browser leads me to a "This page cannot be reached" error.

![CfdG3dU](https://github.com/thomiceli/opengist/assets/118329232/135c2580-5d71-4125-ba03-8e7bf82ac2d8)

Not sure what's going on, but the rest of the site seems to work fine. Only page I'm having issues with is the revisions tab.

**Comment by thomiceli** [comment]
Hi, it's most likely Opengist could not parse the `git log` command.

Could you please cd into the opengist home in your filesystem (most likely `~/.opengist` or `/opengist` on Docker), then in `repos`, find the repository where you have this problem, and please paste the result of this command

```
git --no-pager log --no-color -p --format="format:c %H%na %aN%nm %ae%nt %at" --shortstat HEAD
```

**Comment by Aetherinox** [comment]
fatal: detected dubious ownership in repository at '/home/git/gist/repos/aetherinox/0a36f42c25f841b7a401e5c4c97fd2ea'
To add an exception for this directory, call:
```
	git config --global --add safe.directory /home/git/gist/repos/aetherinox/0a36f42c25f841b7a401e5c4c97fd2ea
```

**Comment by thomiceli** [comment]
Actually there is nothing wrong with the log (_even tho I'm confident the log parser does not cover every edge cases and is not really that stable_), just forgot to add some `$` in the templates... pretty dumb by me
