### ISSUE TITLE
Configuration for not allowing unauthorized page views.

### ISSUE THREAD

**Issue by crueber** [thomiceli/opengist#12]
This is a follow up on #8 , so that it's recorded separately. Taking all the gists private, essentially.

I recognize that there is currently an 'unlisted' option, but it would be nice to be able to have a configuration that would make the whole system private. So that if you were not authenticated, it would just display a page that said something like "Please log in to view gists" or something along those lines. Or maybe just show a log in screen right off the bat, and not allow any viewership until they have their own user to log in.

Fits nicely together with the configuration to disable registration, so that you can have a completely private gist system.

Thanks!

**Comment by thomiceli** [comment]
I see, its a good idea to me.

**Comment by stefanoschrs** [comment]
Another option here (but more complicated) is to have a private visibility type in addition to unlisted & public, so that only the creator and collaborators can access it.
