### ISSUE TITLE
Configuration with YAML file doesn't work on docker

### ISSUE THREAD

**Issue by ptman** [thomiceli/opengist#125]
https://github.com/thomiceli/opengist/blob/master/docs/configuration/index.md#configuration-via-yaml-file

https://github.com/thomiceli/opengist/blob/master/docker/entrypoint.sh

**Comment by thomiceli** [comment]
Hi, do you mean you modified the `config.yml` inside the container ? I can make it work if the use case is needed.

**Comment by UlyssesZh** [comment]
@thomiceli Hi! Is there a documentation about how we can use config.yml with Docker?

**Comment by ptman** [comment]
So I tried something like `docker run -v $(pwd)/config.yaml:/config.yaml opengist:1 --config /config.yaml`. The container starts fine, but opengist isn't started with the parameter --config /config.yaml, so the custom config file doesn't have any effect. And looking at entrypoint.sh, I can see that parameters aren't passed.

**Comment by ptman** [comment]
Thank you. Are you planning a new release?
