### ISSUE TITLE
Option to create a new version if the name of the gist already exist

### ISSUE THREAD

**Issue by PeterXQChen** [thomiceli/opengist#127]
I've been wanting to use opengist to be some sort of a version control for my codes but its tedious to look for a specific gist and then update the code on that gist to create a vew version, it would be amazing if we could just simply type the same name and if it already exist, just create a new version of the existing one rather than creating an entirely new gist.

**Comment by thomiceli** [comment]
There is some use cases where you want to the same title for multiple gists. You could just save the URL of the gist instead ?

**Comment by PeterXQChen** [comment]
I can see that which is why having a global option to overwrite if an existing one exists would make sense.

I could bookmark the URL but I have hundreds of them but I will always have the filename available.
