### ISSUE TITLE
Is it possible to add files after the gist is created?

### ISSUE THREAD

**Issue by alexlehm** [thomiceli/opengist#140]
I recently had a gist where someone asked me if I want to add a license file as they wanted to use it and I didn't find an option to add an additional file once the gist is created.

It works when the gist is created but not afterwards.

**Comment by Juliaria08** [comment]
@alexlehm It, is. In the right there's a button with a pencil which says edit.

**Comment by alexlehm** [comment]
i am sorry, i missed the edit function
