### ISSUE TITLE
[Feature] Is there an API?

### ISSUE THREAD

**Issue by alexlehm** [thomiceli/opengist#141]
Is there an API to create new gists, essentially I want to do something like a 0x0 upload with a script to create a gist on my account from a single file from the shell.

**Comment by thomiceli** [comment]
https://github.com/thomiceli/opengist/blob/master/docs/usage/init-via-git.md

**Comment by alexlehm** [comment]
I made a small upload script to create an opengist via shell command

https://gist.tilde.green/alexlehm/01121ed96b4a49c9a28f42f5762eb791

(quite aptly on an opengist instance)
