### ISSUE TITLE
HTTP Login with federated accounts

### ISSUE THREAD

**Issue by alexlehm** [thomiceli/opengist#142]
When using federated account like gitea, login with HTTP login is not possible since there is no password set (at least I am not aware of any), is it possible to set a PAT to be able to log in for http pushes or to access private repos?

Or if gitea supports that, a device login could work that provides an auth token

**Comment by thomiceli** [comment]
Agreed, or maybe be able to set a password after the oauth sign up

**Comment by alexlehm** [comment]
After considering it a bit further, i think for most uses a single random password that you can activate in settings page would be fine, that you can reset if necessary. the whole oauth client thing is a bit too complicated I guess

**Comment by thomiceli** [comment]
> Edit: the other benefit is that I could just capture `stdin` and make a simple `POST` request via `curl` and not have to deal with making a git repo and pushing just to share one file. :D

I understand the need of a PAT, but I'm failing to see how is that a benefit you could get using a PAT ? (maybe i'm tired)

**Comment by alexlehm** [comment]
> > Edit: the other benefit is that I could just capture `stdin` and make a simple `POST` request via `curl` and not have to deal with making a git repo and pushing just to share one file. :D
> 
> I understand the need of a PAT, but I'm failing to see how is that a benefit you could get using a PAT ? (maybe i'm tired)

that would require a PAT login that uses http basic so that you can create a gist with a single curl command, something like

    curl -F text=@- -u username:PAT --basic https://gist.domain.com/

**Comment by thomiceli** [comment]
> > > Edit: the other benefit is that I could just capture `stdin` and make a simple `POST` request via `curl` and not have to deal with making a git repo and pushing just to share one file. :D
> > 
> > 
> > I understand the need of a PAT, but I'm failing to see how is that a benefit you could get using a PAT ? (maybe i'm tired)
> 
> that would require a PAT login that uses http basic so that you can create a gist with a single curl command, something like
> 
> ```
> curl -F text=@- -u username:PAT --basic https://gist.domain.com/
> ```
> 
> and that could return the gist url name

Nevermind i was indeed tired

**Comment by samagana** [comment]
I am not sure if the original issue here was resolved. I still don't see the feature of having a PAT on Opengist settings

**Comment by alexlehm** [comment]
I have started using it on a site that uses SSO shortly after the update became available and it works fine, I cannot remember how it set it up though
