### ISSUE TITLE
[Feature] Docs on importing gists from GitHub

### ISSUE THREAD

**Issue by alyssadev** [thomiceli/opengist#143]
I figured out how to import gists from GitHub, via cloning bare repos and adding database rows. Demo instance at [gist.aly.pet](https://gist.aly.pet). It would be nifty to have this (pulling in all gists for the linked github user with one click) as a feature in the UI of course, but I've done this first for now I guess. I started documenting the process for a PR for `docs/usage` but ran out of steam. This issue is so I don't lose track of this progress and others can use it before proper documentation is written. Below is my bash_history and python_history after I got it working.

**caveat for anyone wanting to use this**, I started from a fresh instance of opengist each time (deleting the config dir and letting it regenerate, then creating a user and stopping it immediately after). If you happen to want to run this on an existing instance, make sure you adjust `n+1` to include `+<highest ID already in table>`.

```bash
# perhaps there's an easier way to get all the gist data (i.e all pages, for all specified users) for import in one file so no more requests are needed
cd repos/aly/
curl https://api.github.com/users/alyssadev/gists?per_page=100 | jq '.[] | .git_pull_url' -r | while read p; do git clone --bare "$p"; done
curl https://api.github.com/users/blha303/gists?per_page=100 | jq '.[] | .git_pull_url' -r | while read p; do git clone --bare "$p"; done
curl https://api.github.com/users/blha303/gists?per_page=100\&page=2 | jq '.[] | .git_pull_url' -r | while read p; do git clone --bare "$p"; done
# removes .git from the end of the bare repo dir names
for i in *; do mv "$i" "${i%.*}"; done
```

```python
from requests import get
from datetime import datetime
import sqlite3
data = get("https://api.github.com/users/alyssadev/gists?per_page=100").json()
data += get("https://api.github.com/users/blha303/gists?per_page=100").json()
data += get("https://api.github.com/users/blha303/gists?per_page=100&page=2").json()
con = sqlite3.connect("../../opengist.db")
cur = con.cursor()
values = [
    (
        n+1,
        row['id'],
        next(iter(row['files'].values()))['filename'],
        "\n".join( get(next(iter(row['files'].values()))['raw_url']).text.split("\n")[:10] ),
        next(iter(row['files'].values()))['filename'],
        row['description'],
        0,
        1,
        len(row['files']),
        int(datetime.fromisoformat(row['created_at'][:-1]).timestamp()),
        int(datetime.fromisoformat(row['updated_at'][:-1]).timestamp())
    ) for n,row in enumerate(data)]
cur.executemany("INSERT INTO gists (id,uuid,title,preview,preview_filename,description,private,user_id,nb_files,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?,?)",values)
con.commit()
```

**Comment by alyssadev** [comment]
here's my draft for `docs/usage/import-from-gist.md`, I'm not happy with the direction it was going, need to plan it out.

Importing your existing gists from GitHub Gist is a little bit of a process. Here are the steps:

1. Run OpenGist once to generate the directory structure and opengist.db, and create a user
2. [Clone bare copies of each repo in the account](#clone)
3. [Create database rows for each repo](#populate)

## Run OpenGist once
This will create the `repos` directory. Switch into `$opengist/repos/$username`.

```bash
$ ls
docker-compose.yml  config  config.yml
$ ls config
log  opengist.db  repos  ssh  tmp
$ cd config/repos
$ mkdir aly
$ cd aly
```

## Clone

Install `curl` and `jq` from your package manager. Then, in the aforementioned directory, run:

```bash
$ curl https://api.github.com/users/alyssadev/gists?per_page=100 | jq '.[] | .git_pull_url' -r | while read p; do git clone --bare "$p"; done
```

**Comment by thomiceli** [comment]
Having a proper import feature implemented on the app would be ideal :)

In the meantime instead of the python script inserting raw data in the database you could 
- clone all repositories with curl and jq as normal repos (non bare) in your tmp folder for example
- For every repo, add a remote to `https://opengist.instance/init` and git push to it (https://github.com/thomiceli/opengist/blob/master/docs/usage/init-via-git.md) and then remove the repo in the tmp folder


May be less janky, i did not tried this yet tho :)

**Comment by alyssadev** [comment]
I tried that first; I ran into two issues:

* the uuids were different (not a dealbreaker on its own but annoying)
* it seems that it fails to import the repos somewhat frequently? I did this:

```bash
curl https://api.github.com/users/alyssadev/gists | jq '.[] | .git_pull_url' -r | while read p; do git clone "$p"; done
for i in `ls`; do echo "$i"; cd "$i"; git remote add gist https://aly:password@gist.aly.pet/init; git push -u gist --all; cd ..; done
```

Based on the messages shown from the git server it would appear to have worked, but then going to `/all` shows some items with no listed preview and clicking on them shows a 404 error. This also applies to clicking on the link provided by the git server. I'm happy to try to reproduce this in another issue.

**Comment by thomiceli** [comment]
Could reproduce this bug, will investigate

**Comment by thomiceli** [comment]
> ```shell
> curl https://api.github.com/users/alyssadev/gists | jq '.[] | .git_pull_url' -r | while read p; do git clone "$p"; done
> for i in `ls`; do echo "$i"; cd "$i"; git remote add gist https://aly:password@gist.aly.pet/init; git push -u gist --all; cd ..; done
> ```

The PR should fix import issues (caused by branch names main/master). I have tried the 2-liner again and every gist is imported.

**Comment by sergeevabc** [comment]
Is it safe to use your demo instance or the uploaded snippets will be lost after a while?

**Comment by alyssadev** [comment]
I meant a demo as in demonstrating for this issue how I had imported my gists from github, it's my personal opengist instance, please don't use it, thanks

**Comment by thomiceli** [comment]
> Is it safe to use your demo instance or the uploaded snippets will be lost after a while?

My demo instance on demo.opengist.io is not safe to use.
