### ISSUE TITLE
Gitea oAuth Fails

### ISSUE THREAD

**Issue by kaysersoze** [thomiceli/opengist#148]
When attempting to authenticate via Gitea oAuth, I always receive the message:

```
Error 400
Bad Request

Cannot complete user auth
```

From looking at the code at https://github.com/thomiceli/opengist/blob/master/internal/web/auth.go#L141C2-L144C3, it appears that this is failing in gothic's `CompleteUserAuth` but I don't' have any way to see _why_ it's failing.

Is this a known issue (with hopefully a simple fix) and/or is there a way for me to see what the exact error that gothic is returning? 

The rest of the flow (ie. redirecting to Gitea, authorizing the application) seems to be working properly.

Thanks in advance.

<img width="358" alt="Screenshot 2023-11-02 at 2 34 44 PM" src="https://github.com/thomiceli/opengist/assets/735028/8b63ba50-dc1d-40ab-843a-608ca1400239">

**Comment by kaysersoze** [comment]
> The error might be written in the callback url ?

At a `OG_LOG_LEVEL` of `trace` I only get the following in the Opengist log:

```
opengist | 6:17PM INF HTTP URI=/oauth/gitea/callback?code=KIOwQCdGB0Q3g8sCUFbeLgfTCWfvHAnEfBktyNf2Y0Za&state=S6_eOnt15-uW6ij7t6mOKvaGT1ZJMLYRPWl2RTfl9ZqIW2wFDucmjcp6jcnWk2iCyPGSCh7t3e4QqiP4IneQgQ%3D%3D ip=192.168.0.XXX method=GET status=400
```

**Comment by yedajiang44** [comment]
[@](https://github.com/thomiceli/opengist/issues/67#issuecomment-1600960211)

**Comment by thomiceli** [comment]
> I'm having the exact same issue using Authentik as oAuth. I think everything is configured correctly in authenthik but i get error 400 in opengist. Any clue?

Does your openid url ends with `/.well-known/openid-configuration` ?

Anyway yes, the error should be more explicit than it is right now

**Comment by graphixillusion** [comment]
> Does your openid url ends with `/.well-known/openid-configuration` ?

Yep, the address ends with that.

**Comment by graphixillusion** [comment]
@thomiceli ok with the new version the error msg is this:

```
Error 400
Bad Request
Cannot complete user auth: securecookie: the value is too long
```

**Comment by SudoVanilla** [comment]
Same here while adding a Codeberg login.

**Comment by thomiceli** [comment]
> Same here while adding a Codeberg login.
> 
> Set redirect URI to `https://opengist.example.com/oauth/gitea/callback` Set Codeberg URL, id and secret as an env variable.
> 
> But logging in with Codeberg results in `Unregistered Redirect URI`.
> 
> > Nice to see at least the GitHub option works fine.

Codeberg is working fine for me.

By any chance did you put `opengist.example.com` in your redirect URI ?

**Comment by graphixillusion** [comment]
With the last 1.6.0 i'm still getting this error using authentik 

Bad Request
Cannot complete user auth: securecookie: the value is too long: 4224

Is there something that can be adjusted authentik side to make it work?

**Comment by thomiceli** [comment]
> With the last 1.6.0 i'm still getting this error using authentik
> 
> Bad Request Cannot complete user auth: securecookie: the value is too long: 4224
> 
> Is there something that can be adjusted authentik side to make it work?

I don't know about authentik at all but I will check



> > > Same here while adding a Codeberg login.
> > > Set redirect URI to `https://opengist.example.com/oauth/gitea/callback` Set Codeberg URL, id and secret as an env variable.
> > > But logging in with Codeberg results in `Unregistered Redirect URI`.
> > > > Nice to see at least the GitHub option works fine.
> > 
> > 
> > Codeberg is working fine for me.
> > By any chance did you put literally `opengist.example.com` in your redirect URI ?
> 
> That is an example, but I used my actual domain.

What version of Codeberg do you use ?

**Comment by thomiceli** [comment]
> With the last 1.6.0 i'm still getting this error using authentik
> 
> Bad Request Cannot complete user auth: securecookie: the value is too long: 4224
> 
> Is there something that can be adjusted authentik side to make it work?



@graphixillusion what if you only select 'profile' on your authentik provider scopes ?

<img width="610" alt="Screenshot 2024-01-05 at 05 21 24" src="https://github.com/thomiceli/opengist/assets/27960254/c8d983dd-f82c-4f84-ab1d-62bf561222de">

**Comment by graphixillusion** [comment]
> > With the last 1.6.0 i'm still getting this error using authentik
> > Bad Request Cannot complete user auth: securecookie: the value is too long: 4224
> > Is there something that can be adjusted authentik side to make it work?
> 
> @graphixillusion what if you only select 'profile' on your authentik provider scopes ?
> 
> <img alt="Screenshot 2024-01-05 at 05 21 24" width="610" src="https://private-user-images.githubusercontent.com/27960254/294394622-c8d983dd-f82c-4f84-ab1d-62bf561222de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTc1NTYsIm5iZiI6MTcwNDQ1NzI1NiwicGF0aCI6Ii8yNzk2MDI1NC8yOTQzOTQ2MjItYzhkOTgzZGQtZjgyYy00Zjg0LWFiMWQtNjJiZjU2MTIyMmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyMjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlM2ExZjc1YmJmYWEwNTNmMjIyZWY3ZDIxZjg4MmM0YTI2ZGM5MDFlZGQyMDkwMDAwZDIwMTgzOTYzMjQ3NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qrqvjKF8tM-N1VK5qKjgdibVCGOAZiXy82J0SWCTWLc">

Selecting only profile in the scopes section i have this error:

Error 400
Bad Request
Cannot complete user auth: securecookie: the value is too long: 4128

**Comment by thomiceli** [comment]
> > > Same here while adding a Codeberg login.
> > > Set redirect URI to `https://opengist.example.com/oauth/gitea/callback` Set Codeberg URL, id and secret as an env variable.
> > > But logging in with Codeberg results in `Unregistered Redirect URI`.
> > > > Nice to see at least the GitHub option works fine.
> > 
> > 
> > Codeberg is working fine for me.
> > By any chance did you put literally `opengist.example.com` in your redirect URI ?
> 
> That is an example, but I used my actual domain.

@SudoVanilla Can you ensure, when you create your Codeberg oauth application, that this option is checked ?

![Screenshot 2024-01-08 at 00 10 24](https://github.com/thomiceli/opengist/assets/27960254/010ef56c-df5b-4188-b1a8-680bd2440230)

**Comment by SudoVanilla** [comment]
![image](https://github.com/thomiceli/opengist/assets/51213244/66bc0546-a5b4-449e-9b2d-04b92759b6db)

This option was not ticked. 
Now it works!

**Comment by GhaziTriki** [comment]
@thomiceli it looks like the issue is back. Everything was working fine until I upgrade gitea and opengist. I get `Unregistered Redirect URI`. I double check everything, I don't see any issue.
