### ISSUE TITLE
[Feature] Change Default Gist Visibility

### ISSUE THREAD

**Issue by wkeiuluf** [thomiceli/opengist#152]
It would be nice if you could change the default gist visibility.

On GitHub Gists at least, I changed to "Secret" (equivalent to Unlisted) once and it stayed that way.

But this has to be more than just for the web GUI, need to be able to configure that default from when uploading via the terminal as well. Perhaps an account setting?

**Comment by thomiceli** [comment]
For the web GUI, I believe a cookie could hold the visibility value used to create the last gist

For the terminal, maybe using query params would be a thing, e.g. `localhost:6157/init?private`
