### ISSUE TITLE
Indentation doesn't work properly

### ISSUE THREAD

**Issue by jbonadiman** [thomiceli/opengist#16]
I don't know if this is related with only one file format or more, I just started using the app (awesome job, btw! 🥰).
When I visualize my shell script, it shows up like this:

![image](https://user-images.githubusercontent.com/18357636/234426957-0de83e61-40e2-488f-b2cb-9fea59034863.png)
(I'm using the ".sh" extension and my indentation is set to 2 spaces. I even tried to update this information but it didn't "save" - I'll open another issue for that later)

But my file is actually formatted like this:
![image](https://user-images.githubusercontent.com/18357636/234427494-1273158a-6df9-4817-b28e-09970391762e.png)

I tried to manually set indentation from 2 to 4 spaces, but it didn't change anything in the visualization.

**Comment by thomiceli** [comment]
Hi and thank you! 

Currently it behaves like Github Gist and a bit like Vim : when you press tab it indents with the current settings (size and type). 
Only the tabs size change dynamically when you change the settings, that's pretty fair for me (atm) because it could be tricky to convert space and tabs.

That said the problem might come from somewhere else since your indentation in the first screen seems to be only one space ..?

**Comment by jbonadiman** [comment]
Yeah, I realized later that that option sets the tabs size during editting, which makes sense.
But the visualization still looks a bit off. I used 4 spaces in the entire file, but specially inner indents look like got 1 space. And when I edit the file I see the 4 spaces again, so the information is still there.

I really liked your project and I'd love to contribute, so I tried looking into the frontend to see if I spot the error but I don't get shit about it. I'll try to help with the backend instead 😅

**Comment by thomiceli** [comment]
Are you using Opengist through a proxy or something that "optimize" html by removing spaces ? Also what browser are you using ? Seems to be front-related

**Comment by jbonadiman** [comment]
> Are you using Opengist through a proxy or something that "optimize" html by removing spaces ? Also what browser are you using ? Seems to be front-related

Those are very good questions and I'm not sure about that... I'm using Firefox (112.0.1) and I'm proxying using nginx with the following config:
`server {
    listen                 443 ssl;
    server_name            <domain>;

    client_max_body_size   10M;

    ssl_certificate <path>;
    ssl_certificate_key <path>;

    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        proxy_pass              http://localhost:6157/;

        proxy_read_timeout      600s;
        proxy_send_timeout      600s;
    }
}`

**Comment by Maronato** [comment]
In case someone else comes here with the same issue, @thomiceli's idea was spot on and I was able to fix it by disabling Cloudflare's HTML auto minify:

![Screenshot 2023-09-04 at 22 25 33](https://github.com/thomiceli/opengist/assets/19658460/a151068b-297c-439b-b036-a104e2ec0e55)
