### ISSUE TITLE
Feature Request: Allow Imprint and Data Privacy / TOS pages

### ISSUE THREAD

**Issue by MrGeneration** [thomiceli/opengist#163]
Hey,

first of all: Thank you very much for this project and your effort!

I believe the option (optional) to provide imprint and data privacy pages may be a big plus.
A gist doesn't solve this in my opinion, as in some countries you're required to have this information with 1-2 clicks.

Feel free to close if you disagree :)

**Comment by thomiceli** [comment]
https://github.com/thomiceli/opengist/blob/dev-1.7/docs/configuration/custom-links.md

Releasing 1.7 soon

**Comment by thomiceli** [comment]
By the way, thanks for the donation <3

**Comment by MrGeneration** [comment]
Thank you for your time and effort! 🙏
