### ISSUE TITLE
Any plan for 2FA support?

### ISSUE THREAD

**Issue by Anduin2017** [thomiceli/opengist#165]
For security concerns, we need 2FA support for this... Is there any plan for 2FA? Thanks!!

**Comment by lf-** [comment]
I would suggest just standing up an identity provider like authelia, kanidm, or similar, then you can have nice auth with 2fa everywhere and centralized user management.

**Comment by thomiceli** [comment]
I like the idea of a passkey actually

**Comment by Anduin2017** [comment]
Thank you for the contribution!!!
