### ISSUE TITLE
Gist editing options don't persist

### ISSUE THREAD

**Issue by jbonadiman** [thomiceli/opengist#17]
I tried updating my gist's wrap and indent options but these options are not persisted. Could see it through the request:

![image](https://user-images.githubusercontent.com/18357636/234428635-9217fa07-8127-4bfb-9387-523907a62ebe.png)

**Comment by thomiceli** [comment]
The options are meant only for the editor, but i guess we could persist the tab size and the wrap mode to the database.

**Comment by jbonadiman** [comment]
> The options are meant only for the editor, but i guess we could persist the tab size and the wrap mode to the database.

Yes, I think it would be nice to not have to change these options every time I edit the gist 😊
