### ISSUE TITLE
Feature Request: Return remote-url of created repo (by push) or allow setting the id of a newly created gist

### ISSUE THREAD

**Issue by bernhard-da** [thomiceli/opengist#178]
Hi @thomiceli. First of, thanks a lot for creating this wonderful and useful piece of software! Today I spent a bit of time to try to make use of initializing gists via git push (documented [here](https://github.com/thomiceli/opengist/blob/master/docs/usage/init-via-git.md)) which generally works well. To make scripting a bit easier, it would be great if the
```
git push -u origin master
```
could somehow be wrapped into an API-call so that it actually returns the newly created Gist-url; Currently the created url (together with further instructions) is only printed in the output.
```
remote: Your new repository has been created here: {opengist.url}/{id}
remote: If you want to keep working with your gist, you could set the remote URL via:        
remote: git remote set-url origin {opengist.url}/{id}
```
If there was any way to get the {id} after the push-command or by allowing to set {id} directly by allowing something like
```
git remote add origin {opengist.url}/{id}/init
```
it would be much easier to automate the process of batch-importing.

**Comment by thomiceli** [comment]
I went for something like this, involving Git push options

```shell
git push -o url=mygist # Will set the URL to https://opengist.example.com/user/mygist
```

**Comment by bernhard-da** [comment]
@thomiceli great, thanks a lot!
