### ISSUE TITLE
No syntax highlighting for .bat

### ISSUE THREAD

**Issue by jbonadiman** [thomiceli/opengist#18]
Currently there's no syntax highlighting for .bat files. Is it possible to add support for it?

**Comment by thomiceli** [comment]
Can you show how you have created your bat file ? It's working perfectly fine to me https://opengist.thomice.li/thomas/d9953acf898d41fab9e15676979b4e3a

**Comment by thomiceli** [comment]
The syntax highlighting also works with lowercase letters, do you have errors in the console?

**Comment by jbonadiman** [comment]
I don't know in which screen should I look for console errors, but in the main screen of the gist there is none.
By the way, my gist is open, so you can check it here: https://gist.bonadiman.dev/greenteafox/c800ea5b9a9047029e7750e9d0ca38ee

**Comment by jbonadiman** [comment]
Thanks for the support! I'd never figure that out myself. I end up creating a Configuration Rule that disables html minifying just for this hostname (under Rules > Configuration Rules). It fixed the indentation issue on #16, but the syntax highlighting issue still persists.

**Comment by thomiceli** [comment]
I get it, you put an extra space at the end of the file, that's why it has trouble to detect the syntax highlight.. If you trim your file name, it might work. 
I will improve the file extension detection.
