### ISSUE TITLE
Add an invitation feature for closed registration

### ISSUE THREAD

**Issue by LorenDB** [thomiceli/opengist#180]
First, thanks for the awesome paste app! It looks and works great! However, I think it would be great if Opengist had an invitation feature, so you could block general signups but grant accounts to individual users. In my opinion, the best way to do this would be to generate either an invite token (a la [Matrix](https://ems-docs.element.io/books/element-cloud-documentation/page/token-based-registration)) or an invite link. The administrator could create a token/link and send it to the user who wanted an account. It would probably also be good to add an automatic invite expiration to lessen the chances that somebody gains unauthorized access to somebody else's unused invitation.

**Comment by thomiceli** [comment]
A link with an expiration datetime and/or usage limit would be nice.
