### ISSUE TITLE
Taskfile support

### ISSUE THREAD

**Issue by HeCorr** [thomiceli/opengist#2]
[Task](https://taskfile.dev) is a Make alternative written in Go, which makes it a lot easier to install in non-Unix platforms such as Windows.

I propose the creation of a Taskfile which would allow users to execute the installation commands without the need for Make.

I can create a PR for this later today :)

**Comment by thomiceli** [comment]
Hi, i heard about Task but i never actually tried to play with it; i would be glad to see a PR about it :)

**Comment by HeCorr** [comment]
Hi, my apologies for taking so long to tackle this. I am working on it now.

**Comment by thomiceli** [comment]
Hi, no problem and thank you

**Comment by jolheiser** [comment]
Another option that I've seen which is popular is [just](https://just.systems).
