### ISSUE TITLE
Search function is not working anymore 

### ISSUE THREAD

**Issue by mariushosting** [thomiceli/opengist#202]
With the latest update the search function is not working anymore. @thomiceli

**Comment by thomiceli** [comment]
Just in case, you have to index all the gists from the admin panel

**Comment by mariushosting** [comment]
> Just in case, you have to index all the gists from the admin panel

This works, only the healthcheck is not working in the version 1.6.0

**Comment by thomiceli** [comment]
What error do you have?

**Comment by mariushosting** [comment]
> What error do you have?
![Untitled](https://github.com/thomiceli/opengist/assets/37554361/1ee78e8f-495f-49ef-907d-9368c86f9602)
Container is marked as running in Portainer instead of healthy.

It works in the healthy status only If I manually add the healthcheck in the compose as per the example below.

```
    healthcheck:
      test: curl -f http://localhost:6157/ || exit 1

```

**Comment by thomiceli** [comment]
Ah I see I forgot to add an `HEALTHCHECK` instruction in the Dockerfile
