### ISSUE TITLE
Authentik OIDC: "Cannot complete user auth: securecookie: the value is too long: 4140"

### ISSUE THREAD

**Issue by nervous-inhuman** [thomiceli/opengist#212]
This issue was previously disscussed in https://github.com/thomiceli/opengist/issues/148, however I'm moving the discussion here so it can be found more easily, and that there won't be two conversations about two separate issues happening in one thread at once.

When trying to sign-in through Authentik, the user receives the following error:

![image](https://github.com/thomiceli/opengist/assets/8982584/cf28fe9f-49ea-4488-b753-339444595ac4)

There is also a discussion happening in the upstream project that opengist uses for OAuth in Go: https://github.com/markbates/goth/issues/463

**Comment by thomiceli** [comment]
i thought about FilesystemStore also, but I have to make sure it's properly working

**Comment by thomiceli** [comment]
Also considering a way to choose Redis for the session system but it might add a small complexity to maintain the infrastructure as a whole
