### ISSUE TITLE
Securing Self Hosted Installation

### ISSUE THREAD

**Issue by netlander** [thomiceli/opengist#217]
Hi All,

Great application (as a longtime user of Gitea and still waiting for a gist feature).

The integration with Gitea was seamless but after looking around and searching the docs I couldn't find a way to disable user registration and completely close the server to the outside world.

Is it possible to disable user registration?

Thanks

**Comment by thomiceli** [comment]
Yes, in the admin settings you have a switch to disable registration

**Comment by netlander** [comment]
That's the first place I'd have liked to check but where is this admin settings page? I don't see it, here is my installation version:

```
    image: ghcr.io/thomiceli/opengist:1
```

**Comment by netlander** [comment]
Ok now that I've figured ouot that the first user is the Admin, things look more like it. I may be wrong but the docs don't make this clear and as I was relying on Gitea to provide users the Admin feature was not enabled.

Closing the issue.
