### ISSUE TITLE
OIDC does not work with some responses

### ISSUE THREAD

**Issue by mpldr** [thomiceli/opengist#235]
When authenticating with my IdP, I get the following error served with a side of 404 page:

`Cannot complete user auth: securecookie: the value is too long: 4456`

**Comment by mpldr** [comment]
Quick update: goth has a closed issue, that suggests creating a custom gorilla session store. I wonder if ephemeral sessions would be sufficient. If so, a simple map+cleanup might be sufficient.

**Comment by 42wim** [comment]
got the same issue when testing this today :)

You can use sessions.NewFilesystemStore and set `store.MaxLength(math.MaxInt64)`
Make a folder cookies in your /opengist first

And change this code in internal/web/server.go 

-       store *sessions.CookieStore
+       store *sessions.FilesystemStore

....

-       store = sessions.NewCookieStore([]byte("opengist"))
+       store = sessions.NewFilesystemStore(path.Join(os.Getenv("OG_OPENGIST_HOME"), "cookies"), []byte("opengist"))
+       store.MaxLength(math.MaxInt64)

This should fix it, I'll try to make a PR later

**Comment by mpldr** [comment]
I bypassed the issue by using an ECC key for signing the token, so no 
hurry from my sie, but if its an easy fix, all the better!

-- 
Moritz Poldrack
https://moritz.sh

**Comment by thomiceli** [comment]
Same as #212

**Comment by thomiceli** [comment]
Please try the latest release, I can't reproduce the bug anymore with authentik
