### ISSUE TITLE
[Feature Request]: Disable registration

### ISSUE THREAD

**Issue by jiriks74** [thomiceli/opengist#262]
Hello,
I'm setting up the project and it looks so good! Can't way to try it out.

But I've got a use case that is not covered by the current config options. I'd like to allow users **only** from my Gitea instance. I've setup OAuth and it's working but I cannot find an option to disable user registration outside of OAuth.

It would really help if I was able to do so.

**Comment by jiriks74** [comment]
Closing because the first account created has an admin panel where this can be turned off.

I didn't see anything like this in the docs so there wasn't a reason to look for an admin panel.

**Comment by thomiceli** [comment]
You're right, some docs about this should be added
