### ISSUE TITLE
[BUG]: Markdown preview button missing when editing a gist

### ISSUE THREAD

**Issue by jiriks74** [thomiceli/opengist#265]
When creating a new gist, or a new file in that gist, a `Preview` button is present:
![image](https://github.com/thomiceli/opengist/assets/54378412/f6e23ea9-54be-4f5a-8ee3-d1d631b97c04)

However the button is not present when editing the gist (`.md` file):
![image](https://github.com/thomiceli/opengist/assets/54378412/6f63620f-4722-464c-a8ba-c41e6a760d0b)

But after editing the filename (eg. changing the file extension from `.md ` to `.m` and back to `.md`) makes the button appear again.
![image](https://github.com/thomiceli/opengist/assets/54378412/efd016d8-78ea-42c0-b129-6ff61fc9207c)

## Steps to reproduce

1. Go to create a new gist
2. Select `test.md` as a filename
3. See the `Preview` button
4. Add some file contents to be able to create a gist
5. Create the gist
6. Edit the gist
7. See that no `Preview` button is present
8. Edit the filename (remove the `d` at the end and put it back)
9. See that the `Preview` button appeared

**Comment by thomiceli** [comment]
Fixed by #259

**Comment by jiriks74** [comment]
Oh sorry I totally missed that one! I didn't get it in the docker image so I didn't realize it was already dealt with. Sorry for the useless issue.

**Comment by thomiceli** [comment]
No problem :)
