### ISSUE TITLE
HTML entities with markdown and automatically publishing gists when edited

### ISSUE THREAD

**Issue by f97** [thomiceli/opengist#27]
Hi @thomiceli, I love opengist! However, I have some issues:

- Markdown code tag will show HTML entities

```
cat /dev/null > /etc/profile.d/linux-login.sh && touch ~/.hushlogin
```

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/110044923/236649916-cf13e158-ac4a-49b9-94d7-42560ecbfc1f.png">

Expected result: The code will display correctly, same as on GitHub

- With `Unlisted` gists, after I save changes, they are automatically published

Expected result: With `Unlisted` gists, saving changes will not automatically publish them.

Thanks ❤️

**Comment by thomiceli** [comment]
Hi and thank you :)

For your second issue I'm not sure to follow, what do you mean by changes published ? Changes committed to the git repository ?

**Comment by f97** [comment]
> For your second issue I'm not sure to follow, what do you mean by changes published ? Changes committed to the git repository ?

I changed them from web GUI.

**Comment by thomiceli** [comment]
> > For your second issue I'm not sure to follow, what do you mean by changes published ? Changes committed to the git repository ?
> 
> I changed them from web GUI.

Unlisted gists just means you have to get the url to access them, they are not "public". Now when you make changes from the web GUI there is no such concept like a draft, they are committed directly.
