### ISSUE TITLE
Opengist Container Shutdown Randomly After update to version v1.7.2

### ISSUE THREAD

**Issue by mariushosting** [thomiceli/opengist#273]
Opengist Container Shutdown Randomly After update to version v1.7.2

The container automatically and randomly shut down from time to time and need to restart the container from time to time.

@thomiceli

**Comment by thomiceli** [comment]
No logs outputted ?

**Comment by mariushosting** [comment]
`github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).mergerLoop(0xc000514008)
	/root/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.4.0/index/scorch/merge.go:133 +0x638 fp=0xc000696fc8 sp=0xc000696e50 pc=0xc45858
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Open.gowrap3()
	/root/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.4.0/index/scorch/scorch.go:206 +0x25 fp=0xc000696fe0 sp=0xc000696fc8 pc=0xc51cc5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000696fe8 sp=0xc000696fe0 pc=0x4715c1
created by github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Open in goroutine 1
	/root/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.4.0/index/scorch/scorch.go:206 +0x145
goroutine 50 gp=0xc00050c8c0 m=nil [runnable]:
syscall.Syscall6(0x36, 0xf, 0x6, 0x5, 0xc000b13cbc, 0x4, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:91 +0x39 fp=0xc000b13c40 sp=0xc000b13be0 pc=0x4c7999
syscall.setsockopt(0xc000b13cd4?, 0xc000b13d00?, 0x4ec3f2?, 0xc000c6c000?, 0x0?)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1488 +0x33 fp=0xc000b13c90 sp=0xc000b13c40 pc=0x4c7053
syscall.SetsockoptInt(...)
	/usr/local/go/src/syscall/syscall_unix.go:462
internal/poll.(*FD).SetsockoptInt(0xc000b13ce8?, 0xc000b13d40?, 0x89024b?, 0x37e11d600?)
	/usr/local/go/src/internal/poll/sockopt.go:17 +0xf8 fp=0xc000b13cf8 sp=0xc000b13c90 pc=0x4ec3d8
net.setKeepAlivePeriod(0xc00060bd80, 0xc000b13da8?)
	/usr/local/go/src/net/tcpsockopt_unix.go:18 +0x5c fp=0xc000b13d50 sp=0xc000b13cf8 pc=0x892c7c
net.(*TCPConn).SetKeepAlivePeriod(0xc000c6c000, 0xc000580008?)
	/usr/local/go/src/net/tcpsock.go:214 +0x2c fp=0xc000b13d80 sp=0xc000b13d50 pc=0x89154c
github.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x4489c0?})
	/root/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:1001 +0x66 fp=0xc000b13db8 sp=0xc000b13d80 pc=0xf5d0c6
github.com/labstack/echo/v4.(*tcpKeepAliveListener).Accept(0xdc39b4?)
	<autogenerated>:1 +0x25 fp=0xc000b13dd0 sp=0xc000b13db8 pc=0xf63505
net/http.(*onceCloseListener).Accept(0xc000ad4c60?)
	<autogenerated>:1 +0x24 fp=0xc000b13de8 sp=0xc000b13dd0 pc=0xde6124
net/http.(*Server).Serve(0xc000145b30, {0x27c67c8, 0xc000918008})
	/usr/local/go/src/net/http/server.go:3255 +0x33e fp=0xc000b13f18 sp=0xc000b13de8 pc=0xdc383e
github.com/labstack/echo/v4.(*Echo).Start(0xc0001e18c8, {0xc000738000, 0xc})
	/root/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:691 +0xd2 fp=0xc000b13f58 sp=0xc000b13f18 pc=0xf5b112
github.com/thomiceli/opengist/internal/web.(*Server).Start(0xc000b84020)
	/opengist/internal/web/server.go:361 +0xbc fp=0xc000b13fc8 sp=0xc000b13f58 pc=0x11d831c
github.com/thomiceli/opengist/internal/cli.init.func5.gowrap1()
	/opengist/internal/cli/main.go:33 +0x25 fp=0xc000b13fe0 sp=0xc000b13fc8 pc=0x11df7c5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000b13fe8 sp=0xc000b13fe0 pc=0x4715c1
created by github.com/thomiceli/opengist/internal/cli.init.func5 in goroutine 1
	/opengist/internal/cli/main.go:33 +0x6d
goroutine 52 gp=0xc00050cc40 m=nil [IO wait]:
runtime.gopark(0x31be580?, 0xc000291220?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00069dcd8 sp=0xc00069dcb8 pc=0x43f36e
runtime.netpollblock(0x20?, 0x408946?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:573 +0xf7 fp=0xc00069dd10 sp=0xc00069dcd8 pc=0x4380f7
internal/poll.runtime_pollWait(0x7f0c0d351c90, 0x72)
	/usr/local/go/src/runtime/netpoll.go:345 +0x85 fp=0xc00069dd30 sp=0xc00069dd10 pc=0x46c0a5
internal/poll.(*pollDesc).wait(0xc?, 0x321e680?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc00069dd58 sp=0xc00069dd30 pc=0x4e4f27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00060b900)
	/usr/local/go/src/internal/poll/fd_unix.go:611 +0x2ac fp=0xc00069de00 sp=0xc00069dd58 pc=0x4ea2cc
net.(*netFD).accept(0xc00060b900)
	/usr/local/go/src/net/fd_unix.go:172 +0x29 fp=0xc00069deb8 sp=0xc00069de00 pc=0x87df69
net.(*TCPListener).accept(0xc000291220)
	/usr/local/go/src/net/tcpsock_posix.go:159 +0x1e fp=0xc00069dee0 sp=0xc00069deb8 pc=0x8928de
net.(*TCPListener).Accept(0xc000291220)
	/usr/local/go/src/net/tcpsock.go:327 +0x30 fp=0xc00069df10 sp=0xc00069dee0 pc=0x891ad0
github.com/thomiceli/opengist/internal/ssh.listen(0xc0001441e0)
	/opengist/internal/ssh/run.go:58 +0x1a9 fp=0xc00069dfc8 sp=0xc00069df10 pc=0xfe2ec9
github.com/thomiceli/opengist/internal/ssh.Start.gowrap1()
	/opengist/internal/ssh/run.go:46 +0x25 fp=0xc00069dfe0 sp=0xc00069dfc8 pc=0xfe2ce5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00069dfe8 sp=0xc00069dfe0 pc=0x4715c1
created by github.com/thomiceli/opengist/internal/ssh.Start in goroutine 51
	/opengist/internal/ssh/run.go:46 +0xe5
goroutine 125 gp=0xc000485c00 m=nil [IO wait]:
runtime.gopark(0x10?, 0x10?, 0xf0?, 0xc5?, 0xb?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc0007ec5a8 sp=0xc0007ec588 pc=0x43f36e
runtime.netpollblock(0x4c59b8?, 0x408946?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:573 +0xf7 fp=0xc0007ec5e0 sp=0xc0007ec5a8 pc=0x4380f7
internal/poll.runtime_pollWait(0x7f0c0d351b98, 0x72)
	/usr/local/go/src/runtime/netpoll.go:345 +0x85 fp=0xc0007ec600 sp=0xc0007ec5e0 pc=0x46c0a5
internal/poll.(*pollDesc).wait(0xc00017de80?, 0xc0006eaca1?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc0007ec628 sp=0xc0007ec600 pc=0x4e4f27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00017de80, {0xc0006eaca1, 0x1, 0x1})
	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a fp=0xc0007ec6c0 sp=0xc0007ec628 pc=0x4e621a
net.(*netFD).Read(0xc00017de80, {0xc0006eaca1?, 0xc0007ec748?, 0x46df50?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25 fp=0xc0007ec708 sp=0xc0007ec6c0 pc=0x87bf85
net.(*conn).Read(0xc000918708, {0xc0006eaca1?, 0xc0001ee840?, 0x321e680?})
	/usr/local/go/src/net/net.go:179 +0x45 fp=0xc0007ec750 sp=0xc0007ec708 pc=0x889945
net.(*TCPConn).Read(0x317a3e0?, {0xc0006eaca1?, 0xa0f33b?, 0x5f5e100?})
	<autogenerated>:1 +0x25 fp=0xc0007ec780 sp=0xc0007ec750 pc=0x89a4a5
net/http.(*connReader).backgroundRead(0xc0006eac90)
	/usr/local/go/src/net/http/server.go:681 +0x37 fp=0xc0007ec7c8 sp=0xc0007ec780 pc=0xdb8657
net/http.(*connReader).startBackgroundRead.gowrap2()
	/usr/local/go/src/net/http/server.go:677 +0x25 fp=0xc0007ec7e0 sp=0xc0007ec7c8 pc=0xdb8585
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0007ec7e8 sp=0xc0007ec7e0 pc=0x4715c1
created by net/http.(*connReader).startBackgroundRead in goroutine 124
	/usr/local/go/src/net/http/server.go:677 +0xba
usermod: no changes`

**Comment by mariushosting** [comment]
I'm forced to use the restart policy **restart: always** instead of restart: on-failure:5
if I don't use always as restart polict I wake up in the morning that the opengist container is stopped.

**Comment by mariushosting** [comment]
> No logs outputted ?

Issue completely solved with version 1.7.5
