### ISSUE TITLE
It is recommended to add AI support

### ISSUE THREAD

**Issue by badboy-tian** [thomiceli/opengist#283]
It is recommended to add support for llama or chatgpt, so that you can use ai to summarize the code and ask some questions.

**Comment by thomiceli** [comment]
You mean integrate a chatbot on the app ?
Not sure about this

**Comment by Aetherinox** [comment]
Yeah, there's a lot of other areas that would help Opengist be better than it already is, but at least to me, AI is like down at # 1034 on that list.
