### ISSUE TITLE
how to change the page?

### ISSUE THREAD

**Issue by jueshifuqing** [thomiceli/opengist#287]
great project! 
Im fisher.
I run with docker. but I can't find the web page file in docker,which folder the pages in? like home page, edit page? thx

**Comment by thomiceli** [comment]
Not sure to understand, you want to access the source of the HTML pages ? If so you can't if you're using the Docker image or the binary, since they are embedded directly inside the binary. If you wish to modify html templates you have to take the source and recompile it with your changes.
