### ISSUE TITLE
export repos

### ISSUE THREAD

**Issue by jueshifuqing** [thomiceli/opengist#290]
how the user export his all repos?
how the admin export all the repos?

how I can make comments on other peoples code?  error correcting
or create a team to work together?

thks

**Comment by thomiceli** [comment]
Repositories are stored in the Opengist home in the `repos` directory, you can create an archive containing that.

For the rest you probably want something more advanced like Gitea or Gitlab

**Comment by jueshifuqing** [comment]
thank you. I understand.
