### ISSUE TITLE
Admin option to use shorter UUIDs

### ISSUE THREAD

**Issue by TheZoker** [thomiceli/opengist#295]
Would be amazing, if there was an option to use shorter IDs, so for example `a94283` instead of `a94283d903484fa1bcee8cc66612b15c`. For an instance with a lot of members and for high security I understand, that this may be unwanted, but for me the long url is not visually appealing.  

Maybe some system like git uses for the commits, where each commit has a long ID and a short one. And an option in the admin interface to use the short version would be amazing!

**Comment by thomiceli** [comment]
Maybe simply keeping the long uuid but gists may be queryable by with the beginning of the uuid
