### ISSUE TITLE
when run in the linux and docker , Chinese garbled characters

### ISSUE THREAD

**Issue by jueshifuqing** [thomiceli/opengist#296]
when run in the linux and docker , Chinese garbled characters（such like "\345\225\212\345\217\221.sql"）

when run in windows , Chinese text is ok.

is this a bug?

**Comment by yqs112358** [comment]
Met this problem too.

Reproduce: 
1. Build an opengist instance in Docker
2. Then create a gist named by any CJK language, like "中文名.txt"
3. After creation, click the "raw file" button in the gist page
4. Error

**Comment by thomiceli** [comment]
> Met this problem too.
> 
> Reproduce:
> 
>     1. Build an opengist instance in Docker
> 
>     2. Then create a gist named by any CJK characters, like "中文名.txt"
> 
>     3. After creation, click the "raw file" button in the gist page
> 
>     4. Error

Thanks for the reproduction steps

**Comment by awkj** [comment]
Need add Content-Typ tell browser, the encoding use utf-8, chinese deafult use GBK-8 encoding
