### ISSUE TITLE
Allow to delete files again after adding them

### ISSUE THREAD

**Issue by TheZoker** [thomiceli/opengist#297]
Since we can add new files in the UI, it would also be amazing to remove them again. So maybe show a little red X in the top right for all the files except for the first one.

**Comment by thomiceli** [comment]
You have a button to delete a file when editing a gist

![image](https://github.com/thomiceli/opengist/assets/27960254/548662b9-1435-4074-98a3-7decf86d64c1)

**Comment by TheZoker** [comment]
Yes but not on the create new first view right?
