### ISSUE TITLE
Integrate with gitea/forgejo

### ISSUE THREAD

**Issue by ptman** [thomiceli/opengist#3]
Would you consider integration. It would help not having to have separate users and two different git/ssh services

**Comment by jolheiser** [comment]
Even just OAuth2 could be something to look at. 

https://github.com/markbates/goth makes it fairly easy and has a Gitea driver (and others that may be of interest as well!) which could be used. 🙂

**Comment by thomiceli** [comment]
> Even just OAuth2 could be something to look at.
> 
> https://github.com/markbates/goth makes it fairly easy and has a Gitea driver (and others that may be of interest as well!) which could be used. 🙂

I was definitely looking to add at some point login from OAuth providers like Gitea or Github. Thanks for the link i will check it out. 🙂

**Comment by poVoq** [comment]
Alternatively LDAP (maybe specifically [LLDAP](https://github.com/lldap/lldap) ) would be nice and a bit more generic.

**Comment by ptman** [comment]
it seems my problem might be more related to how opengist uses docker
