### ISSUE TITLE
Anonymous user can easily find unlisted gist by simply using search box

### ISSUE THREAD

**Issue by npirmez** [thomiceli/opengist#309]
Anonymous user can easily find unlisted git just by trying some keywords in the search box.
In my opinion, he shouldn't have access to these git without being logged or knowing the exact URL.
Or is it a normal way of working ?
Thanks for this great tool.

**Comment by npirmez** [comment]
gist not git of course

**Comment by thomiceli** [comment]
Thanks for the sponsor btw :)

**Comment by npirmez** [comment]
I can replicate…

https://demo.opengist.io/search?q=
(going in search box, and hit ‘enter’


De : Thomas Miceli ***@***.***>
Envoyé : mardi 3 septembre 2024 17:26
À : thomiceli/opengist ***@***.***>
Cc : Nicolas Pirmez ***@***.***>; Author ***@***.***>
Objet : Re: [thomiceli/opengist] Anonymous user can easily find unlisted gist by simply using search box (Issue #309)


Can't replicate, take this gist: https://demo.opengist.io/thomas/5a5c022d27a4486f965efa03239fc610

It doesn't appear (if you're not logged as thomas) in the search results:
https://demo.opengist.io/search?q=package+web
https://demo.opengist.io/search?q=user%3Athomas
https://demo.opengist.io/search?q=title%3Asession
etc.
