### ISSUE TITLE
Option to disable registration

### ISSUE THREAD

**Issue by ptman** [thomiceli/opengist#33]

**Comment by thomiceli** [comment]
Already implemented

**Comment by ptman** [comment]
In that case where is it documented?

**Comment by dch** [comment]
the first user to sign up is the admin, so log in, go to user profile, then `admin` -> `configuration` > and toggle `disable signup`

![Image](https://github.com/user-attachments/assets/3d20bd4a-3ce4-41f3-a941-7a4ad8f071ee)

[added as this is the #1 search item via google for this question]
