### ISSUE TITLE
"Services" must be a mapping error when building from docker image at this page: https://opengist.io/docs/installation/docker.html

### ISSUE THREAD

**Issue by Ars0nistt** [thomiceli/opengist#356]
Correct .yml file contents: 

services:
   opengist:
        image: ghcr.io/thomiceli/opengist:1.7
        container_name: opengist
        restart: unless-stopped
        ports:
             - "6157:6157"
             - "2222:2222"
         volumes:
             - ./data:/opengist"

**Comment by thomiceli** [comment]
Are you referring to `services.opengist.environment` ? Thats just a way to show an example of the docker compose, you still need to tweak it a little.
