### ISSUE TITLE
[Bug]: Syntax error in gist embed script

### ISSUE THREAD

**Issue by jiriks74** [thomiceli/opengist#374]
Embedding a Gist results in the following error:

```
Uncaught SyntaxError: missing ) after argument list
```

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/d721675f-8323-495a-9f76-1d937416fafd)

</details>

> [!Note]
> The error disappears after I remove the script so the error isn't from the website itself.

---

Info:
- OS:         `Docker`
- Version: `v1.8.1`

**Comment by thomiceli** [comment]
@jiriks74 can you give me an example of your content or maybe try to build Opengist from this branch `fix/escaping-embed-gists` to check if you have the error again ?

**Comment by jiriks74** [comment]
> try to build Opengist from this branch fix/escaping-embed-gists to check if you have the error again ?

I can build a local docker image but not right now.

> can you give me an example of your content

Sure. I tried to embed [this gist](https://opengist.stefka.eu/jiriks74/element14-libreelec) I used the code that was provided by OpenGist:

```html
<script src="https://opengist.stefka.eu/jiriks74/element14-libreelec.js"></script>
```
