### ISSUE TITLE
Use Sqlite WAL mode by default

### ISSUE THREAD

**Issue by poVoq** [thomiceli/opengist#40]
WAL mode is a lot faster especially on CoW filesystems like btrfs or zfs, see:

https://wiki.tnonline.net/w/Blog/SQLite_Performance_on_Btrfs

It is also pretty much the standard for modern SQLite use.

Would be nice if this was enabled by default (currently it isn't).

**Comment by thomiceli** [comment]
I see, maybe an option in config.yml to choose the journal mode might be better
