### ISSUE TITLE
Alternative way to configure Docker container?

### ISSUE THREAD

**Issue by poVoq** [thomiceli/opengist#41]
I am trying to run the Docker container without docker-compose (Using Podman and Quadlet) and while it works fine in general, it does not seem to understand the concatenated (?) ENV variables that are in the docker-compose example.

I tried various standard ways of passing individual ENV variables to the container, but it just doesn't seem to take them.

I am a bit at a loss right now how exactly docker-compose handles these multiple ENV variables or is it some sort of huge single ENV variable of the entire config file?

Would be nice if there was an example how to use it without docker-compose just by passing the normal "-e" docker parameters or maybe it is possible to add a second volume where one can place a config.yml to be loaded automatically by the container?

Thanks!

**Comment by thomiceli** [comment]
Indeed I'm aware that, currently, the config via environment variables is not the best. The current behavior is one single env var named CONFIG for the whole `config.yml`. 
I will work on this to have a env var per item in the `config.yml`, maybe like how Gitea does it (https://docs.gitea.com/installation/install-with-docker#managing-deployments-with-environment-variables), so you will be able easily overwrite some config, or use Docker `-e` in your case

**Comment by poVoq** [comment]
Just a small feedback: with 1.4.1 this runs great with Podman now and I was able to configure all the additional parameters via ENV variables to integrate it with my Forgejo (Gitea) instance.

Thanks a lot!

**Comment by thomiceli** [comment]
> Just a small feedback: with 1.4.1 this runs great with Podman now and I was able to configure all the additional parameters via ENV variables to integrate it with my Forgejo (Gitea) instance.
> 
> Thanks a lot!

Glad you like the project :)
