### ISSUE TITLE
[Suggestion] Add your own Logo

### ISSUE THREAD

**Issue by mariushosting** [thomiceli/opengist#48]
It would be interesting to be able to put your own logo in the top left corner instead of the default one.

**Comment by Jas-SinghFSU** [comment]
For those wanting to do this until it's officially implemented; you can do so by injecting css into your reverse proxy (NGINX).

It's not a pretty solution, but it works.

If you're using NGINX, you can add the following below your existing config
```
    location / {
        <... your existing config>

        ############################
        # Custom CSS
        ############################
        proxy_set_header Accept-Encoding "";

        # your custom CSS rules go here
        sub_filter
        '</head>'
        '<style> .flex-shrink-0 a .object-cover { content: url(your_image_url_here); } </style>
        </head>';
    }
```

Make sure that you DON'T include quotes in your image url.
