### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by nillebor** [thomiceli/opengist#52]
Is it possible to translate opengist? 
It would be enough, with a language file what can be edited
I would like to translate it into German.

It would be nice if this opportunity is created.

**Comment by thomiceli** [comment]
Would be nice indeed, but would require a lot of workf for different translations. I can try to setup the translation system for now

**Comment by nillebor** [comment]
Yes, that would be enough. There will definitely be a user for each language. And English remains as the standard.
In contrast to other apps, this is still very clear at opengist

I would be nice it if you could implement it.

**Comment by thomiceli** [comment]
Hi @nillebor, you can create a German translation based on this file : https://github.com/thomiceli/opengist/blob/master/internal/i18n/locales/en-US.yml
