### ISSUE TITLE
[Suggestion] Search Function

### ISSUE THREAD

**Issue by mariushosting** [thomiceli/opengist#55]
It would be great to have a search button to find the gist when there are many.

**Comment by thomiceli** [comment]
It is planned, i'm just thinking how i will implement it ? Search by name only ? User ? Code ? etc.

**Comment by Cyberes** [comment]
> Search by name only ? User ? Code ?

Why not have it as an option next to the search bar or in the admin settings? I'd like to search by code/content but @mariushosting seems to want to search by name. A simple dropdown would probably satisfy us both.

**Comment by Cyberes** [comment]
Wow, that was quick.
