### ISSUE TITLE
Private gists

### ISSUE THREAD

**Issue by Cyberes** [thomiceli/opengist#59]
Hey, nice project!

Just a quick suggestion: add private gists. We've got public and unlisted, but no way to set a gist as truly private.

**Comment by thomiceli** [comment]
Is there something you miss with the unlisted visibility you would get with a private one ?

**Comment by Cyberes** [comment]
Well, let's say that I have a gist that only I will access. Maybe I just want to store a file on the server that I will use later. If I don't plan on sharing it I'd like it to be 100% private (maybe its a config file or something with passwords in it).
