### ISSUE TITLE
Prefix env vars

### ISSUE THREAD

**Issue by jolheiser** [thomiceli/opengist#62]
Consider prefixing the env vars `CONFIG` (and `DEV`) with `OG_` to avoid collisions.

I'd be happy to submit a small PR if you agree.

**Comment by thomiceli** [comment]
Agreed for `DEV`, but i would like to deprecate `CONFIG` since its behavior is weird and might be counter intuitive ?

**Comment by jolheiser** [comment]
I am fine with whichever you prefer.
If this were a CLI tool I might think differently, but a flag is easy enough to set in a service file.

**Comment by jolheiser** [comment]
I just now realized `CONFIG` actually expects valid YAML? Just skimming I thought it was supposed to be a path to a config file. 

If that is the case, I agree with deprecating it. :sweat_smile:
