### ISSUE TITLE
Non-CGO SQLite

### ISSUE THREAD

**Issue by jolheiser** [thomiceli/opengist#65]
I am making an issue in case you are interested, but also in case anyone else is interested.

I have [changes](https://github.com/thomiceli/opengist/compare/master...jolheiser:modernc?expand=1) in a [branch](https://github.com/jolheiser/opengist/tree/modernc) that use the non-CGO version of SQLite, which just makes cross-compilation a bit easier at the cost of some performance (whether it is significant or not may be subjective).

At least for me it's worth it to not have to deal with CGO. If you use docker it's probably a mostly moot point, so YMMV.

---

If you are interested and/or want to allow both, that could potentially also work with some build tag tricks.

**Comment by thomiceli** [comment]
It could be interesting to have both I guess, choosing which one you want to use at compile time. 
As long it's not exhausting to maintain in the long run...
