### ISSUE TITLE
lighttpd reverse proxy configuration

### ISSUE THREAD

**Issue by graphixillusion** [thomiceli/opengist#72]
Hi there. As the title says i'm trying to make it works with a reverse proxy using lighttpd. I've tried with this configuration:

```
$HTTP["url"] =~ "^/opengist($|/)" {
  proxy.server = ( "" => ( (
    "host" => "127.0.0.1",
    "port" => 6157
  ) ) ),
  proxy.forwarded = ( "for" => 1,
                      "host" => 1,
                      "by" => 1
  ),
  proxy.header = (
      "map-urlpath" => (
         "/opengist/"  => "/",
         "/opengist" => ""
       )
  )
}
```

and i can reach the homepage but it cannot access all the other resources becouse it wants files from host/assets.

Any help? Thank you!

**Comment by thomiceli** [comment]
Hello, after investigation, it's quite normal that you can't access the assets, in fact the site links won't even work properly as each of them points to a URL that starts with `/`, so defining a sub url from your proxy would break the site.
The site urls should start with `external-url` from the config for example, i can work on that or you can open a PR if you want :)

**Comment by thomiceli** [comment]
One temporary solution would be to go for a sub domain instead.

**Comment by graphixillusion** [comment]
> One temporary solution would be to go for a sub domain instead.

Sadly i don't have control on the domain.

**Comment by graphixillusion** [comment]
@thomiceli any news on this?

**Comment by jasonm23** [comment]
FWIW I have opengist running _fairly_ well behind a lighttpd reverse proxy:

```c
$HTTP["host"] == "gist.gitcodo.hub" {
    proxy.server = ( "" =>
        ( ( "host" => "helios", "port" => 6157 ) )
    )
}
```

Almost everything is working including oauth with my Gitea instance, create, read, update, delete of gists / files all works.  Http and Git repo access works. etc.

The only issue I have is that when editing markdown the `[ Preview ]` button (and subsequent POST request to `/preview`) kills Opengist with:

```log
16:19:52 FTL internal/web/server.go:231 error="code=400, message=missing csrf token in request header"
```

The client receives this as a `500`, as opengist dies, and restarted by systemd, so I'll get `503` and `500` while it's doing that, but no more info.

Not sure what to do next tbh.
