### ISSUE TITLE
Rendering issue when routing to another page

### ISSUE THREAD

**Issue by ksj20** [thomiceli/opengist#73]
The header part is enlarged before rendering the page I intended to go to. (ex. from home to settings page)

I slowered the throttling then disabled it just in case you want to replicate

FYI,
| Program | Version |
|--------|--------|
| Opengist | 1.4.1 |
| Go | go 1.20.4 |
| Git | 2.30.1 | 

Version of NPM packages are equivalent to package.json

**Comment by thomiceli** [comment]
I see, are you using Opengist in dev mode ?

**Comment by ksj20** [comment]
If you are talking about the docker dev image, no I am not using that. 
I git cloned then built the executable locally

**Comment by ksj20** [comment]
Thanks for the update
