### ISSUE TITLE
Allow admin options to be set via environment variables

### ISSUE THREAD

**Issue by owenfiscus** [thomiceli/opengist#74]
First off, great project. I've been looking for something like this for ages and the Gitea OAuth integration is the icing on the cake. I would like to be able to set the settings listed in the _Admin_ area of the application via environment variables.

For example, the _Disable signup_ toggle could be set in a compose file as follows.

``` yaml
OG_DISABLE_SIGNUP: true
```

**Comment by thomiceli** [comment]
Hi, thank you! At first it behaved like this, but please see #5 #8
