### ISSUE TITLE
Allow disabling signups through the admin panel

### ISSUE THREAD

**Issue by crueber** [thomiceli/opengist#8]
First and foremost: Thanks for making a great tool!

It would be nice if I didn't have to mess with the config.yml every time I wanted to turn on/off user registration. It would be great if there was another setting to take the whole of the gist system private (or rather, "authenticated only").

**Comment by thomiceli** [comment]
Thanks :) I think i will move this option to the admin panel (https://github.com/thomiceli/opengist/issues/5#issuecomment-1510414877). Also can you elaborate what do you mean by making the whole gist system private ?

**Comment by crueber** [comment]
@thomiceli Wow! Nice! I was away for the weekend and you already got it! Thanks!

What I meant by making the gist system private... actually, I'll open another ticket, because that really is a separate thing. Thanks again!
