### ISSUE TITLE
[Feature Request] Base URL

### ISSUE THREAD

**Issue by lividhen** [thomiceli/opengist#82]
If there is a way to change this already someone let me know because I couldn't find it 😅.
Could you add a way to change the base url for reverse proxy purposes? I have a bunch of services routed through nginx on the same port which can be accessed through their own base url (eg http://nginx.local/jellyfin). The only way I have found to do this is to change the application base url (if there is another way, again, someone let me know!)
![image](https://github.com/thomiceli/opengist/assets/42221797/7cba37df-55d7-46e1-9c99-b2f46b19f79c)
This is what my nginx config looks like for my reverse proxy, and this directs to 127.0.0.1:6157/opengist which gives a 404 error.

**Comment by thomiceli** [comment]
Hi, set your url in the config `external-url` something like `https://your.domain/opengist`
