### ISSUE TITLE
Support OIDC

### ISSUE THREAD

**Issue by hibare** [thomiceli/opengist#9]
Thank you for the awesome project!!.

I was actually looking for GitHub gist alternatives for some time.
It would be wonderful if Opengist supports OIDC for SSO.

**Comment by thomiceli** [comment]
Thank you! I will look into that

**Comment by poVoq** [comment]
Duplicate of this: https://github.com/thomiceli/opengist/issues/3 I guess.

Although full OIDC support and not just OAuth2 could be added.

**Comment by Maronato** [comment]
@thomiceli this can probably be closed now
